feat(people): add roberto huertas profile to the web
badboy/barcelona.rustfest.eu pull request #2
Opened 2019-05-23 08:19 UTC by robertohuertasm

I reorganized the profiles according to how it was already working but I made some assumptions.
Please correct me if I'm wrong. Local organizers have a priority of 10, core team members 80,
everyone else 99. I guess alphabetic order is used.

re #1

2019-05-29 19:05 UTC, badboy requested changes

2019-05-29 19:05 UTC, badboy commented on _people/robertohuertasm.md
> +name: Florian Gilcher
Wrong name.

2019-05-30 05:24 UTC, robertohuertasm commented on _people/robertohuertasm.md
> +name: Florian Gilcher
Good catch! 😊 Done.

2019-05-30 10:24 UTC, badboy approved these changes

2019-05-30 10:24 UTC, merged