diversity: Add Spanish version of the page
badboy/barcelona.rustfest.eu pull request #20
Opened 2019-08-01 06:42 UTC by ifraixedes

Closes #17

2019-08-01 16:51 UTC, robertohuertasm reviewed
Some suggestions and corrections.

2019-08-01 16:51 UTC, robertohuertasm commented on diversity.es.md
> +RustFest es una de las más grandes conferencias de Rust y respesta la misión de Rust seriamente por mantener una comunidad inclusiva.
```suggestion
RustFest es una de las conferencias más grandes sobre Rust y se toma en serio la misión de Rust de mantener una comunidad inclusiva. 
Ésta se basa en cuatro fundamentos.
```

2019-08-01 16:51 UTC, robertohuertasm commented on diversity.es.md
> +## Presupuesto priorizado en la gente
```suggestion
## Presupuestamos teniendo en cuenta a las personas
```

2019-08-01 16:51 UTC, robertohuertasm commented on diversity.es.md
> +RustFest tiene el objetivo de ofrecer entradas a bajo coste, mientras mantiene una conferencia de calidad. Es la conferencia de Rust más asequible y antigua, con entradas de precio fijo alrededor de
```suggestion
RustFest tiene el objetivo de ofrecer entradas a bajo coste, mientras mantiene una conferencia de calidad. Es la conferencia sobre Rust más asequible y veterana, con entradas a precio fijo alrededor de 100 Euros y entradas a precio rebajado. El precio de la entrada está centrado en un único principio: aunque RustFest no tuviese patrocinadores, se celebraría.
```

2019-08-01 16:51 UTC, robertohuertasm commented on diversity.es.md
> +Aunque no siempre esta garantizado, históricamente, pagamos todos los gastos a nuestros conferenciantes y organizadores para atender a la última RustFests. Siempre pagamos todos los gastos a la gente
```suggestion
Aunque no siempre está garantizado, históricamente, hemos sufragado siempre todos los gastos a nuestros ponentes y organizadores para hacer posible su asistencia al RustFest. En todo caso, siempre pagamos todos los gastos a la gente que no puede permitírselo.
```

2019-08-01 16:51 UTC, robertohuertasm commented on diversity.es.md
> +La última RustFest ha tenido una considerable cantidad de entradas de diversidad (5%). En contraste con otras muchas otras conferencias, hemos empezado a pagar por todos los gastos de viaje y alojami
```suggestion
Las últimas ediciones del RustFest ha tenido una considerable cantidad de entradas de diversidad (5%). En contraposición a otras muchas otras conferencias, hemos empezado a pagar todos los gastos de viaje y alojamiento para el primer conjunto de entradas. Esto incluye viajes transcontinentales. Por otro lado, bajo demanda, pagamos por anticipado los gastos del viaje a los poseedores de entradas de diversidad.
```

2019-08-01 16:51 UTC, robertohuertasm commented on diversity.es.md
> +Es importante para nosotros que los poseedores de entadas de diversidad no tengan ningún problema en atender. Por una conferencia de nuestro rango de precio, los viajes son a menudo más prohibitivo q
```suggestion
Es importante para nosotros que los poseedores de entradas de diversidad no tengan ningún problema para poder atender. Para una conferencia de nuestro rango de precio, el precio del viaje es, a menudo, más prohibitivo que el las entradas.
```

2019-08-01 16:51 UTC, robertohuertasm commented on diversity.es.md
> +Cuando hablamos de esfuerzo en la diversidad de las TI, discapacidad es a menudo olvidada. Nosotros creemos que esto tiene que cambiar. RustFest ha tenido siempre una [declaración de accesibilidad](/
```suggestion
Cuando hablamos de esfuerzo en la diversidad de las TI, la discapacidad es a menudo olvidada. Nosotros creemos que esto tiene que cambiar. RustFest ha tenido siempre una [declaración de accesibilidad](/accessibility/) con la documentación adecuada  por adelantado. Nuestros esfuerzos son cotejados e implementados con gente realmente discapacitada. RustFest siempre tiene una persona responsable de los esfuerzos para la accesibilidad.
```

2019-08-01 16:51 UTC, robertohuertasm commented on diversity.es.md
> +RustFest reconoce que la discapacidad es diversa y trabajara directamente contigo para solucionar todas tus necesidades. Trabajaremos activamente con los problemas conjuntamente contigo.
```suggestion
RustFest reconoce que la discapacidad es diversa y trabajará directamente contigo para solucionar todas tus necesidades. Trabajaremos activamente contigo en resolver cualquier asunto.
```

2019-08-01 16:51 UTC, robertohuertasm commented on diversity.es.md
> +Nosotros siempre aseguramos que los servicios de comida escogidos puedan servir comida apropiada para vegetarianos y veganos y también comida especial bajo solicitud. También intentamos de que puedan
```suggestion
Siempre aseguramos que los servicios de comida escogidos puedan servir comida apropiada para vegetarianos y veganos y también comida especial bajo demanda. También intentamos que pueda servirse comida para gente con otras necesidades dietéticas. Si es posible, buscamos servicios de comida que puedan satisfacer todas estas opciones porque hemos visto que es la manera más fácil de ofrecer comida de calidad a gran escala para todo el mundo.
```

2019-08-01 16:51 UTC, robertohuertasm commented on diversity.es.md
> +Las solicitudes están gestionadas rápidamente y hasta ahora solo hemos tenido una solicitud que no pudimos satisfacer.
```suggestion
Las solicitudes se gestionan diligentemente y, hasta ahora, solo hemos tenido una petición que no pudimos satisfacer.
```

2019-08-01 16:51 UTC, robertohuertasm commented on diversity.es.md
> +Por favor, ten en cuenta que debido a que RustFest es una conferencia que se realiza cada vez en una distinta zona geográfica, solo podemos contratar servicios de comida una vez, lo cual puede siempr
```suggestion
Por favor, ten en cuenta que debido a que RustFest es una conferencia que se realiza cada vez en una zona geográfica distinta, solo podemos trabajar con un servicio de comida una vez, lo cual puede siempre introducir variaciones de una edición a otra.
```

2019-08-01 16:51 UTC, robertohuertasm commented on diversity.es.md
> +RustFest tiene una estricta regla, no se sirve alcohol gratuitamente. Esto incluye rechazar ofertas de ciertos patrocinadores. Hemos encontrado en previas conferencias que ofrecer alcohol gratuito co
```suggestion
RustFest tiene una estricta regla: no se sirve alcohol gratuitamente. Esto incluye rechazar ofertas de ciertos patrocinadores. Hemos visto en conferencias previas que ofrecer alcohol gratuito contribuye a una cultura de festividad agresiva ya que la gente, acabaría bebiendo gratuitamente y comprando más alcohol.
```

2019-08-01 16:51 UTC, robertohuertasm commented on diversity.es.md
> +Por favor ten en cuenta que los alrededores de algunos centros de conferencia es posible que tengan alcohol, pero verificamos que siempre hay disponible buenas y económicas opciones no alcohólicas y
```suggestion
Ten en cuenta que en los alrededores de algunos centros de la conferencia es posible encontrar alcohol a la venta, pero siempre verificamos que hay disponibles opciones no alcohólicas de calidad y económicas y bastante espacio para evitar encontrarse gente embriagada. 
```

2019-08-01 16:51 UTC, robertohuertasm commented on diversity.es.md
> +Tenemos procesos para gestionar con muchas cosas que son un pequeño problema para nosotros, pero son grandes para ti.
```suggestion
Tenemos procesos para gestionar muchas cosas que son pequeños problemas para nosotros, pero grandes para ti.
```

2019-08-01 16:51 UTC, robertohuertasm commented on diversity.es.md
> +No preguntamos por ningún tipo de prueba y siempre asumimos que nos contactaras con buena intención. RustFest está aquí para que pases un buen rato y si tu tienes algún tipo de necesidad, te ayudarem
```suggestion
No exigimos ningún tipo de prueba y siempre asumimos que tus peticiones son de buena fe. RustFest está aquí para que pases un buen rato y si tú tienes algún tipo de necesidad, te ayudaremos de la mejor manera que podamos.
```

2019-08-01 16:51 UTC, robertohuertasm commented on diversity.es.md
> +La comunidad de Rust es joven y RustFest es un proyecto joven. Estamos contentos de recibir cualquier sugerencia sobre (éste y previas) RustFest en cualquier momento. Por favor, contacta con nosotros
```suggestion
La comunidad de Rust es joven y RustFest es un proyecto joven también. Estaremos encantados de recibir cualquier sugerencia sobre (éste y previas) RustFest en cualquier momento. Por favor, contacta con nosotros a través de [team@rustfest.eu](mailto:team@rustfest.eu).
```

2019-08-01 16:51 UTC, robertohuertasm commented on diversity.es.md
> +Si tu ves algo en lo que podemos mejorar, por favor ¡haznos lo saber! Nos ocuparemos de ello. Sí sucede que es algo en lo que te gustaría trabajar, por favor no dudes en contactar con nosotros para h
```suggestion
Si ves algo en lo que podemos mejorar, ¡haznoslo saber, por favor! Nos ocuparemos de ello. Sí resulta que es algo en lo que te gustaría colaborar, por favor no dudes en contactar con nosotros para hacernos saber que quieres formar parte del equipo. Sabemos que las soluciones no son siempre gratuitas y, por tanto, intentaremos dedicar esfuerzos y parte del presupuesto, en la medida de lo posible, a tu tarea.
```

2019-08-01 17:24 UTC, ifraixedes commented on diversity.es.md
> +RustFest es una de las más grandes conferencias de Rust y respesta la misión de Rust seriamente por mantener una comunidad inclusiva.
no se que estaba pensando cunado escribí esto :sweat_smile:

2019-08-01 17:25 UTC, ifraixedes commented on diversity.es.md
> +## Presupuesto priorizado en la gente
Definitivamente me gusta más tu versión.

2019-08-01 17:29 UTC, ifraixedes commented on diversity.es.md
> +Aunque no siempre esta garantizado, históricamente, pagamos todos los gastos a nuestros conferenciantes y organizadores para atender a la última RustFests. Siempre pagamos todos los gastos a la gente
_ponentes_ era la palabra que no me salía.

2019-08-01 17:30 UTC, ifraixedes commented on diversity.es.md
> +Aunque no siempre esta garantizado, históricamente, pagamos todos los gastos a nuestros conferenciantes y organizadores para atender a la última RustFests. Siempre pagamos todos los gastos a la gente
_al RustFest_ sería _a la RustFest_?

2019-08-01 17:32 UTC, ifraixedes commented on diversity.es.md
> +Es importante para nosotros que los poseedores de entadas de diversidad no tengan ningún problema en atender. Por una conferencia de nuestro rango de precio, los viajes son a menudo más prohibitivo q
_más prohibitivo que el las entradas_ => _más prohibitivo que el de las entradas_

2019-08-01 17:44 UTC, ifraixedes commented
@robertohuertasm thanks for your revision, I should have read it after I translated it before pushing it.

2019-08-01 20:22 UTC, robertohuertasm commented on diversity.es.md
> +Aunque no siempre esta garantizado, históricamente, pagamos todos los gastos a nuestros conferenciantes y organizadores para atender a la última RustFests. Siempre pagamos todos los gastos a la gente
Aquí he tenido dudas. Al final he optado por el másculino por que entiendo que la gente cuando habla dice "voy al fullstack fest", porque se entiende Fest como festival. El femenino lo veo raro en este contexto pero claro, quizá el resto lo vea bien. A ver qué opinan @chris-zen, @alberss o @angelmixu.

2019-08-01 20:40 UTC, angelmixu commented on diversity.es.md
> +Aunque no siempre esta garantizado, históricamente, pagamos todos los gastos a nuestros conferenciantes y organizadores para atender a la última RustFests. Siempre pagamos todos los gastos a la gente
A mí no me parece mal el que hay, yo lo que puedo sugerir también es lo siguiente:
"para que puedan atender al último RustFest."
o quizás... "para que puedan atender al evento."

2019-08-01 21:01 UTC, spastorino commented on diversity.es.md
> +RustFest es una de las conferencias más grandes sobre Rust y se toma en serio la misión de Rust de mantener una comunidad inclusiva.
```suggestion
RustFest es una de las conferencias más grandes sobre Rust y se toma en serio la misión de mantener una comunidad inclusiva. 
```

2019-08-01 21:01 UTC, spastorino commented on diversity.es.md
> +Ésta se basa en cuatro fundamentos.
```suggestion
Ésta se basa en cuatro principios.
```

2019-08-01 21:01 UTC, spastorino commented on diversity.es.md
> +RustFest tiene el objetivo de ofrecer entradas a bajo coste, mientras mantiene una conferencia de calidad. Es la conferencia sobre Rust más asequible y veterana, con entradas a precio fijo alrededor
I wouldn't say `veterana` here but also it is the oldest Rust conference? isn't it RustConf?. It's also not the most `asequible` conference, unsure the prices of Asia but Rust Latam was USD 50, sorry guys :).

Also, the website talks about 250 euros, not 100 euros, and doesn't mention discounts as the spanish text do.

```suggestion
RustFest tiene el objetivo de ofrecer entradas a bajo costo sin renunciar a la calidad. Es una de las primeras y más asequibles conferencias sobre Rust, con entradas a un precio alrededor de 100 Eurosl y entradas a precios rebajados. El precio de la entrada está centrado en un único principio: aunque RustFest no tuviese patrocinadores, se realizaría.
```

2019-08-01 21:01 UTC, spastorino commented on diversity.es.md
> +Aunque no siempre esta garantizado, históricamente, pagamos todos los gastos a nuestros conferenciantes y organizadores para atender a la última RustFests. Siempre pagamos todos los gastos a la gente
Encuentro la frase escrita de manera muy rara para mi español. De todas formas mi español tal vez sea de los más raros del mundo :joy:.

Yo escribiría algo así ...
```suggestion
Aunque no siempre esta garantizado, siempre hemos pagamos todos los gastos a nuestros oradores y organizadores para hacer posible su asistencia a RustFest. De todas formas siempre pagaremos todos los gastos a las personas que por una u otra razón no pudieran afrontar los costos.
```

Diganme sí agrego muchos uruguashismos :joy:

2019-08-01 21:01 UTC, spastorino commented on diversity.es.md
> +El excedente de los presupuestos son a menudo invertidos en la comunidad o guardados para la siguiente edición.
```suggestion
El excedente económico, si hubiere, es a menudo invertido en la comunidad o guardados para la siguiente edición.
```

2019-08-01 21:01 UTC, spastorino commented on diversity.es.md
> +Las últimas ediciones del RustFest ha tenido una considerable cantidad de entradas de diversidad (5%). En contraposición a otras muchas otras conferencias, hemos empezado a pagar todos los gastos de
No sé bien qué quiere decir `primer conjunto de entradas` supongo que es una traducción literal de `first batch`, pero para que quede claro el texto sería bueno saber qué pasa con los siguientes batches.

```suggestion
Las últimas ediciones del RustFest han tenido una considerable cantidad de entradas de diversidad (5%). En contraposición a otras conferencias, hemos pagado todos los gastos de viaje y alojamiento para el primer conjunto de entradas. Esto incluye viajes transcontinentales. Por otro lado, de ser necesario, pagamos por anticipado los gastos del viaje a los poseedores de entradas de diversidad.
```

2019-08-01 21:01 UTC, spastorino commented on diversity.es.md
> +Es importante para nosotros que los poseedores de entadas de diversidad no tengan ningún problema en atender. Por una conferencia de nuestro rango de precio, los viajes son a menudo más prohibitivo q
```suggestion
Es importante para nosotros que quién posea entradas de diversidad no tenga ningún problema en asistir. Por una conferencia de nuestro coste, el costo de los viajes es a menudo más difícil de afrontar que el costo de las entradas.
```

2019-08-01 21:01 UTC, spastorino commented on diversity.es.md
> +RustFest reconoce que la discapacidad es diversa y trabajará directamente contigo para solucionar todas tus necesidades. Trabajaremos activamente contigo en resolver cualquier asunto.
No me gusta la idea de escribir que la discapacidad es diversa. Buscaría una forma mejor de decirlo. Supongo que esto es traducción de `disability is diversiry` o algo así, que significa algo medio distinto que lo que dice en español que suena bastante más feo :).

2019-08-01 21:01 UTC, spastorino commented on diversity.es.md
> +RustFest tiene una estricta regla: no se sirve alcohol gratuitamente. Esto incluye rechazar ofertas de ciertos patrocinadores. Hemos visto en conferencias previas que ofrecer alcohol gratuito contrib
```suggestion
RustFest tiene una estricta regla: no se sirve alcohol de manera gratuita. Esto incluye rechazar ofertas de ciertos patrocinadores. Hemos visto en conferencias previas que ofrecer alcohol gratuito contribuye a una cultura de festividad agresiva ya que la gente, acaba bebiendo gratuitamente y comprando más alcohol.
```

2019-08-01 21:01 UTC, spastorino commented on diversity.es.md
> +RustFest reconoce que la discapacidad es diversa y trabajará directamente contigo para solucionar todas tus necesidades. Trabajaremos activamente contigo en resolver cualquier asunto.
```suggestion
RustFest reconoce que la discapacidad es diversidad y trabajará directamente contigo para solucionar todas tus necesidades. Trabajaremos activamente contigo en resolver cualquier asunto.
```

2019-08-02 08:00 UTC, ifraixedes commented on diversity.es.md
> +RustFest tiene el objetivo de ofrecer entradas a bajo coste, mientras mantiene una conferencia de calidad. Es la conferencia sobre Rust más asequible y veterana, con entradas a precio fijo alrededor
> It's also not the most asequible conference, unsure the prices of Asia but Rust Latam was USD 50, sorry guys :).

Can you report that to an issue? this is a translation form the English version which is the source of truth.

Regarding the changes, most of them look good to me except a type in `Euros` and `coste` is fine in Spanish from Spain. @robertohuertasm you suggested changes on this paragraph (my one was too bad) so I think this change is under your assessment.

2019-08-02 08:06 UTC, ifraixedes commented on diversity.es.md
> +Las últimas ediciones del RustFest ha tenido una considerable cantidad de entradas de diversidad (5%). En contraposición a otras muchas otras conferencias, hemos empezado a pagar todos los gastos de
> No sé bien qué quiere decir primer conjunto de entradas supongo que es una traducción literal de first batch, pero para que quede claro el texto sería bueno saber qué pasa con los siguientes batches.

No deberia quedar eso tambien claro en la version English?

2019-08-02 08:07 UTC, ifraixedes commented on diversity.es.md
> +RustFest reconoce que la discapacidad es diversa y trabajará directamente contigo para solucionar todas tus necesidades. Trabajaremos activamente contigo en resolver cualquier asunto.
A mi me parece bién.
@robertohuertasm estás de acuerdo con esto?

2019-08-02 08:10 UTC, ifraixedes commented on diversity.es.md
> +Aunque no siempre esta garantizado, históricamente, pagamos todos los gastos a nuestros conferenciantes y organizadores para atender a la última RustFests. Siempre pagamos todos los gastos a la gente
La de @robertohuertasm suena mejor considerando Español de España.

2019-08-02 08:12 UTC, ifraixedes commented on diversity.es.md
> +El excedente de los presupuestos son a menudo invertidos en la comunidad o guardados para la siguiente edición.
por mi parte no veo mal la existente.
@robertohuertasm alguna objeción?

2019-08-02 08:17 UTC, ifraixedes commented
I don't know why, but I cannot comment this one https://github.com/RustFestEU/barcelona.rustfest.eu/pull/20#discussion_r309891021 in place

I would slightly modify the new suggestion in this way

> Es importante para nosotros que quién posea entradas de diversidad no tenga ningún problema en asistir. Para una conferencia de nuestro preupuesto, el coste de los viajes es a menudo más difícil de afrontar que el coste de las entradas.

2019-08-02 10:16 UTC, robertohuertasm commented on diversity.es.md
> +RustFest es una de las conferencias más grandes sobre Rust y se toma en serio la misión de Rust de mantener una comunidad inclusiva.
@spastorino, esto estaba así en el original. Imagino que querían resaltar que Rust, como comunidad, también tiene esa misión.

2019-08-02 10:21 UTC, robertohuertasm commented on diversity.es.md
> +RustFest tiene el objetivo de ofrecer entradas a bajo coste, mientras mantiene una conferencia de calidad. Es la conferencia sobre Rust más asequible y veterana, con entradas a precio fijo alrededor
I think the same as Ivan. This is a translation so any content issues should be raised as a separated issue. 

Regarding the translation, `coste` sounds better in Spain Spanish than `costo` that has different connotations related to drugs. You wouldn't normally use `costo` like that. The same with `celebrar`. Normally we use it with events, conferences and the like.  `Realizar` is too generic and not really suited for a conference (always from a Spaniard perspective ;D)

2019-08-02 10:22 UTC, robertohuertasm commented on diversity.es.md
> +El excedente de los presupuestos son a menudo invertidos en la comunidad o guardados para la siguiente edición.
Es correcta, había un error entre el singular del sujeto y el tiempo verbal. Por mi commit!

2019-08-02 10:25 UTC, robertohuertasm commented on diversity.es.md
> +Las últimas ediciones del RustFest ha tenido una considerable cantidad de entradas de diversidad (5%). En contraposición a otras muchas otras conferencias, hemos empezado a pagar todos los gastos de
Ok a la traducción. Tampoco tengo claro a lo que se refiere ese `first batch`. No sé si la idea original es que se han pagado todos los gastos `desde` el primer `lote de entradas` o qué. Ciertamente, no queda claro, en español, qué quiere decir esto.

2019-08-02 10:28 UTC, robertohuertasm commented on diversity.es.md
> +RustFest reconoce que la discapacidad es diversa y trabajará directamente contigo para solucionar todas tus necesidades. Trabajaremos activamente contigo en resolver cualquier asunto.
Totalmente de acuerdo.

2019-08-02 10:30 UTC, robertohuertasm commented
Tampoco puedo comentar en el que comenta @ifraixedes. Creo que sugerí una versión alternativa previa. No sé si se habrá aceptado. Quizás esa sea la causa. Habría que revisar mi sugerencia y la de @spastorino y hacer un mix. En general, lo veo bien excepto el uso de `costo`.

2019-08-02 11:21 UTC, spastorino commented on diversity.es.md
> +RustFest es una de las conferencias más grandes sobre Rust y se toma en serio la misión de Rust de mantener una comunidad inclusiva.
A mi me había parecido medio redundante pero entiendo el punto.

2019-08-02 11:23 UTC, spastorino commented on diversity.es.md
> +RustFest tiene el objetivo de ofrecer entradas a bajo coste, mientras mantiene una conferencia de calidad. Es la conferencia sobre Rust más asequible y veterana, con entradas a precio fijo alrededor
Perdón que en este caso comenté en inglés, en este punto todavía no sabía que estaban haciendo los comentarios en español.
Todo lo que puse son ideas o sugerencias y obviamente con un español raro que es el que yo uso :). Pasenle el filtro español España y vean si hay algo de lo que puse que tiene sentido en general :)

2019-08-02 11:24 UTC, spastorino commented on diversity.es.md
> +El excedente de los presupuestos son a menudo invertidos en la comunidad o guardados para la siguiente edición.
:+1:

2019-08-02 11:28 UTC, spastorino commented
@robertohuertasm @ifraixedes debería haber hecho un comentario general diciendo que, tomen con pinzas muchos de mis comentarios. Tomenlo como la visión de alguien que usa un español distinto. A algunas cosas les hice cambios porque acá suenan muy raras pero entiendo que para ustedes no y este evento es en Barcelona :). Por eso, tomen con pinzas las cosas y sientanse libre de descartar absolutamente todas mis ideas.

2019-08-02 14:13 UTC, robertohuertasm commented on diversity.es.md
> +RustFest tiene el objetivo de ofrecer entradas a bajo coste, mientras mantiene una conferencia de calidad. Es la conferencia sobre Rust más asequible y veterana, con entradas a precio fijo alrededor
```suggestion
RustFest tiene el objetivo de ofrecer entradas a bajo coste sin renunciar a una conferencia de calidad. Es una de las conferencias más veteranas y asequibles sobre Rust, con entradas alrededor de los 100 Euros y otras a precio rebajado. El precio de la entrada está centrado en un único principio: aunque RustFest no tuviese patrocinadores, el evento se podría celebrar igualmente.
```

2019-08-02 14:14 UTC, robertohuertasm commented on diversity.es.md
> +RustFest tiene el objetivo de ofrecer entradas a bajo coste, mientras mantiene una conferencia de calidad. Es la conferencia sobre Rust más asequible y veterana, con entradas a precio fijo alrededor
He cogido trozos de @spastorino y los he metido en una nueva sugerencia para hacer el cambio.

2019-08-02 14:54 UTC, robertohuertasm commented
Nueva versión con algunas sugerencias de @spastorino incluídas. Echadle un último vistazo si podéis.

2019-08-02 16:01 UTC, robertohuertasm commented
@badboy, @angelmixu and I think that this is good enough to be merged. So if someone has something to say, please speak now or forever hold your peace. 😜

2019-08-02 17:30 UTC, badboy requested changes
Can't speak about the text, I trust you on that one.
The links need to be adjusted though.

2019-08-02 17:30 UTC, badboy commented on diversity.es.md
> +permalink: /diversity/es
```suggestion
permalink: /diversity/es/
```

Needs the trailing slash here.

2019-08-02 17:30 UTC, badboy commented on diversity.es.md
> +[English version](https://barcelona.rustfest.eu/diversity)
```suggestion
### [English version](/diversity/)
```

2019-08-02 17:30 UTC, badboy commented on diversity.md
> +[Ver en español](https://barcelona.rustfest.eu/diversity/es)
```suggestion
### [Ver en español](/diversity/es/)
```

2019-08-03 09:40 UTC, robertohuertasm commented
Done!

2019-08-03 10:02 UTC, badboy approved these changes
:shipit:

2019-08-07 07:33 UTC, merged