Add schedule
badboy/barcelona.rustfest.eu pull request #39
Opened 2019-10-23 22:31 UTC by dns2utf8

* [x] Fix the blog loading on too many pages
* [ ] Add schedule
    * [ ] add @skade 
    * [ ] add @zeenix

2019-10-23 22:47 UTC, dns2utf8 commented
Please check your links and descriptions

![Bildschirmfoto am 2019-10-23 um 22 45 45](https://user-images.githubusercontent.com/739070/67439858-031d1980-f5e7-11e9-861e-a3edbeec0ab7.png)

2019-10-23 23:02 UTC, dns2utf8 commented on _layouts/default.html
> -    </script>
Don't load the blog posts on all pages except the `index.html`

2019-10-24 07:29 UTC, RafaelaWetzel commented
Florian's last name is written wrong, it should be "Gilcher"

2019-10-24 09:30 UTC, dns2utf8 commented
> Florian's last name is written wrong, it should be "Gilcher"

Thank you, it is fixed

2019-10-24 11:11 UTC, badboy commented
We got a new picture from Zeeshan, we should swap it out

2019-10-24 11:20 UTC, badboy requested changes

2019-10-24 11:20 UTC, badboy commented on schedule.md
>  ### Exact schedule
Let's remove the whole block of text above this (and this heading).
Let's also add the links to the talks and workshop overview as we have that on the talks and workshop sites itself.

2019-10-24 11:21 UTC, badboy commented
Oh. and I swapped out the picture

2019-10-26 13:40 UTC, badboy approved these changes

2019-10-26 13:40 UTC, merged